apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    run: mongo
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 31514
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: mongo
  sessionAffinity: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: registry.ng.bluemix.net/alexandersspaceibm/mongo
        name: mongo
        env:
          # Use secret in real usage
        - name: mongo_root_password
          value: password
        ports:
        - containerPort: 9080
          name: mongo
